# Generated by Django 3.2 on 2021-05-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_comment_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date',)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
